version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(name)s(%(lineno)d) - %(message)s"
  error:
    format: "%(asctime)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
  rotating_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: restapi.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console,rotating_file_handler]